---
#The playbook to provision vpc and their instnaces.

- hosts: localhost
  vars:
   environ: stage
  tasks:
  
   - name: Include the variables specific to the vpc
     include_vars: envs/{{ environ }}
   
   - name: Create the VPC 
     local_action:
        module: ec2_vpc
        state: present
        region: "{{ ec2_region }}"
        resource_tags:
            Environment: "{{ environ }}"
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        cidr_block: "{{ vpc_cidr_block }}"
        subnets: "{{ vpc_subnets }}"
        dns_support: true
        dns_hostnames: true
        internet_gateway: "{{ vpc_internet_gateway|string }}"
        route_tables: "{{ vpc_route_tables_public }}"
        wait: yes
     register: vpc
   
   - set_fact:
      maps: "{{ lookup('template', 'templates/subnet_maps.j2')|from_yaml }}"

   - name: Create the security group for the VPC
     ec2_group:
       name: "{{ item.name }}"
       description: "{{ item.desc }}"
       vpc_id: "{{ vpc.vpc_id }}"
       region: "{{ ec2_region }}"
       ec2_access_key: "{{ ec2_access_key }}"
       ec2_secret_key: "{{ ec2_secret_key }}"
       rules: "{{ item.rules }}"
     with_items: vpc_security_groups
     register: sec_groups
   

   - name: Create the LoadBalancer
     ec2_elb_lb:
      state: present
      name: "{{ vpc_pub_lb_name }}"
      subnets: "{{ maps['web'].split(',') }}"
      listeners: "{{ vpc_pub_lb_listeners }}"
      health_check: "{{ vpc_pub_lb_health_check }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      region: "{{ ec2_region }}"
     register: lb
   
   - name: Create the rds subnet group
     rds_subnet_group:
      state: present
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      name: "{{ rds_subnet_name }}"
      description: "{{ rds_subnet_description }}"
      subnets: "{{ maps['db'].split(',') }}"
 
   - name: Create the master RDS instance 
     rds:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      command: create
      instance_name: "{{ rds_instance_name }}"
      db_engine: MySQL
      size: "{{ rds_size }}"
      instance_type: "{{ rds_db_type }}"
      username: "{{ rds_username }}"
      password: "{{ rds_password }}"
      backup_retention: "{{ rds_backup_retention }}"
      db_name: "{{ rds_db_name }}"
      multi_zone: true
      subnet: "{{ rds_subnet_name }}"
      port: "{{ rds_db_port }}"
      vpc_security_groups: "{{ sec_groups.results[1].group_id }}"
      wait: true
      wait_timeout: 1500

   - name: Get RDS facts
     rds:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      command: facts
      instance_name: "{{ rds_instance_name }}"
     register: rds_facts

   - name: Create the Instance's in Zone 1 for this vpc 
     ec2:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ keypair }}"
      assign_public_ip: true
      instance_type: "{{ instance_type }}"
      image: "{{ image_id }}"
      vpc_subnet_id: "{{ maps['web'].split(',')[0] }}"
      wait: true
      instance_tags:
        Name: "{{ environ + '_web_server1' }}"
        role: "{{ environ + '_web_server' }}"
        env: "{{ environ }}"
      exact_count: "{{ exact_count }}"
      count_tag:
        Name: "{{ environ + '_web_server1' }}"
      group: "{{ vpc_security_groups[0].name }}"
     register: ec2_zone1
   

   - name: Create the Instance's in Zone 2 for this vpc
     ec2:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ keypair }}"
      assign_public_ip: true
      instance_type: "{{ instance_type }}"
      image: "{{ image_id }}"
      vpc_subnet_id: "{{ maps['web'].split(',')[1] }}"
      wait: true
      instance_tags:
        Name: "{{ environ + '_web_server2' }}"
        role: "{{ environ + '_web_server' }}"
        env: "{{ environ }}"
      exact_count: "{{ exact_count }}"
      count_tag:
        Name: "{{ environ + '_web_server2' }}"
      group: "{{ vpc_security_groups[0].name }}"
     register: ec2_zone2

   - name: Wait for the Instance's ssh to be ready
     wait_for: host={{ item.public_ip }} port=22 state=started
     with_flattened:
        - ec2_zone1.tagged_instances 
        - ec2_zone2.tagged_instances 

   - name: Add the dynamic inventory
     add_host: hostname={{ item.public_ip }} groups=webservers
     with_flattened:
        - ec2_zone1.tagged_instances 
        - ec2_zone2.tagged_instances 

   

- hosts: webservers
  remote_user: root
  vars: 
   environ: stage
  pre_tasks:
   - ec2_facts:
     register: foo
   - name: Include the variables specific to the vpc
     include_vars: envs/{{ environ }}
  roles:
   - common
   - base-apache
   - web
  post_tasks:
   - name: Instance Register
     local_action: ec2_elb
     args:
      region: "{{ ec2_region }}"
      ec2_access_key: "{{ ec2_access_key }}"
      ec2_secret_key: "{{ ec2_secret_key }}"
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ vpc_pub_lb_name }}"
      state: 'present'

   
